name: expense_tracker_lite
description: Expense Tracker Lite â€¢ Clean Architecture (Two Features)
publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  http: ^1.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatars/
